const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const ALL_24_LEADS = [
  // 1. LINKEDIN
  {
    id: 'lead-john-smith',
    name: 'John Smith',
    jobTitle: 'CTO',
    companyName: 'Nexus Dynamics Corp',
    companyWebsite: 'www.nexusdynamics.com',
    industry: 'IT Services',
    companySize: '51 – 200 employees',
    email: 'john.smith@nexusdynamics.com',
    emailVerified: true,
    phone: '+1 (555) 123-4567',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/john-smith-cloud',
    sourcePlatform: 'LinkedIn',
    originalPostUrl: 'https://www.linkedin.com/posts/john-smith-nexus_sharepoint-m365-migration',
    originalPostSnippet: 'Looking for a SharePoint Implementation Partner !! We are currently seeking a reliable and experienced SharePoint implementation partner company to support an upcoming project focused on enhancing collaboration, document management, and workflow automation. Key areas: SharePoint Online setup, custom development, and Microsoft 365 migration.',
    intentScore: 94,
    budgetSignal: 'High',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'MEETING_BOOKED',
  },
  {
    id: 'lead-david-chen',
    name: 'David Chen',
    jobTitle: 'Chief Information Officer',
    companyName: 'Apex Financial Technologies',
    companyWebsite: 'www.apexfintech.com',
    industry: 'Finance',
    companySize: '1,000+ employees',
    email: 'd.chen@apexfintech.com',
    emailVerified: true,
    phone: '+1 (555) 674-8890',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/david-chen-cio',
    sourcePlatform: 'LinkedIn',
    originalPostUrl: 'https://www.linkedin.com/posts/david-chen-apex_cloud-security-fintech',
    originalPostSnippet: 'Actively scouting partners for enterprise-wide zero trust cloud security architecture implementation across our multi-region AWS footprint.',
    intentScore: 95,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-marcus-vance',
    name: 'Dr. Marcus Vance',
    jobTitle: 'Chief Information Officer',
    companyName: 'Horizon Healthcare Systems',
    companyWebsite: 'www.horizonhealth.org',
    industry: 'Healthcare',
    companySize: '500+ employees',
    email: 'm.vance@horizonhealth.org',
    emailVerified: true,
    phone: '+1 (555) 392-8812',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/dr-marcus-vance-health',
    sourcePlatform: 'LinkedIn',
    originalPostUrl: 'https://www.linkedin.com/posts/marcus-vance-horizon_ehr-hipaa-automation',
    originalPostSnippet: 'Scouting accredited integration partners to automate our EHR patient records and HIPAA-compliant communication pipelines across 14 regional clinics.',
    intentScore: 93,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-sarah-jenkins',
    name: 'Sarah Jenkins',
    jobTitle: 'VP of Engineering',
    companyName: 'CloudStream Software',
    companyWebsite: 'www.cloudstream.io',
    industry: 'Software',
    companySize: '201 – 500 employees',
    email: 's.jenkins@cloudstream.io',
    emailVerified: true,
    phone: '+1 (555) 472-9182',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/sarah-jenkins-cloudstream',
    sourcePlatform: 'LinkedIn',
    originalPostUrl: 'https://www.linkedin.com/posts/sarah-jenkins-kubernetes-devops',
    originalPostSnippet: 'Looking for a specialized DevOps consulting team to migrate our multi-tenant SaaS architecture to Kubernetes and automate our CI/CD deployment pipelines.',
    intentScore: 90,
    budgetSignal: 'Approved',
    urgencyLevel: 'Medium',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },

  // 2. X (TWITTER)
  {
    id: 'lead-priya-nair',
    name: 'Priya Nair',
    jobTitle: 'VP of Engineering',
    companyName: 'CloudTech Inc.',
    companyWebsite: 'www.cloudtech.io',
    industry: 'Software',
    companySize: '201 – 500 employees',
    email: 'priya.nair@cloudtech.io',
    emailVerified: true,
    phone: '+1 (555) 872-9012',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/priya-nair-crm',
    sourcePlatform: 'X (Twitter)',
    originalPostUrl: 'https://x.com/priyanair_tech/status/17892182739182',
    originalPostSnippet: 'Evaluating modern CRM migration and workflow tools to consolidate our sales pipeline. Who is doing great work here?',
    intentScore: 87,
    budgetSignal: 'Approved',
    urgencyLevel: 'Medium',
    decisionMaker: true,
    activeRequirement: true,
    status: 'CONTACTED',
  },
  {
    id: 'lead-alex-rivera',
    name: 'Alex Rivera',
    jobTitle: 'Head of Infrastructure',
    companyName: 'FinEdge Technologies',
    companyWebsite: 'www.finedgetech.com',
    industry: 'Finance',
    companySize: '51 – 200 employees',
    email: 'a.rivera@finedgetech.com',
    emailVerified: true,
    phone: '+1 (555) 619-4820',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/alex-rivera-finedge',
    sourcePlatform: 'X (Twitter)',
    originalPostUrl: 'https://x.com/alexrivera_fin/status/1792849182912',
    originalPostSnippet: 'Looking for recommendations: Need an enterprise-grade low-latency event-driven API middleware team to handle 50k msgs/sec payment processing.',
    intentScore: 91,
    budgetSignal: 'High',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-jessica-taylor',
    name: 'Jessica Taylor',
    jobTitle: 'Director of Product',
    companyName: 'RetailNova Commerce',
    companyWebsite: 'www.retailnova.com',
    industry: 'Retail',
    companySize: '201 – 500 employees',
    email: 'j.taylor@retailnova.com',
    emailVerified: true,
    phone: '+1 (555) 782-9931',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/jessica-taylor-retail',
    sourcePlatform: 'X (Twitter)',
    originalPostUrl: 'https://x.com/jtaylor_commerce/status/1793819284712',
    originalPostSnippet: 'Anyone know great consulting teams who build real-time inventory synchronization between Shopify Plus, ERP, and physical POS systems? DMs open!',
    intentScore: 88,
    budgetSignal: 'Approved',
    urgencyLevel: 'Medium',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-tariq-mansoor',
    name: 'Tariq Al-Mansoor',
    jobTitle: 'Chief Technology Officer',
    companyName: 'SmartLogix AI',
    companyWebsite: 'www.smartlogix.ai',
    industry: 'Logistics',
    companySize: '51 – 200 employees',
    email: 'tariq@smartlogix.ai',
    emailVerified: true,
    phone: '+1 (555) 438-9120',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/tariq-al-mansoor',
    sourcePlatform: 'X (Twitter)',
    originalPostUrl: 'https://x.com/tariq_smartlogix/status/1794719283719',
    originalPostSnippet: 'Urgent: Looking to partner with a team specialized in automated document processing & invoice OCR extraction to integrate with our freight forwarding TMS.',
    intentScore: 89,
    budgetSignal: 'High',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },

  // 3. COMPANY WEBSITES
  {
    id: 'lead-marc-weber',
    name: 'Marc Weber',
    jobTitle: 'Head of Data Infrastructure',
    companyName: 'DataSystems GmbH',
    companyWebsite: 'www.datasystems.eu',
    industry: 'Consulting',
    companySize: '500+ employees',
    email: 'm.weber@datasystems.eu',
    emailVerified: true,
    phone: '+49 30 9182345',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/marc-weber-data',
    sourcePlatform: 'Company Websites',
    originalPostUrl: 'https://datasystems.eu/procurement/rfp-data-warehouse-2025',
    originalPostSnippet: 'Public RFP: Looking for certified data engineering partners for Snowflake and cloud data warehouse modernization.',
    intentScore: 82,
    budgetSignal: 'High',
    urgencyLevel: 'Medium',
    decisionMaker: true,
    activeRequirement: true,
    status: 'CALL_SCHEDULED',
  },
  {
    id: 'lead-amara-okafor',
    name: 'Amara Okafor',
    jobTitle: 'Director of Enterprise IT',
    companyName: 'Sterling Manufacturing',
    companyWebsite: 'www.sterlingmfg.com',
    industry: 'Manufacturing',
    companySize: '1,000+ employees',
    email: 'a.okafor@sterlingmfg.com',
    emailVerified: true,
    phone: '+1 (555) 891-3472',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/amara-okafor-it',
    sourcePlatform: 'Company Websites',
    originalPostUrl: 'https://sterlingmfg.com/procurement/rfp-iot-azure-2026',
    originalPostSnippet: 'Enterprise Procurement Portal Notice: Seeking IoT systems integration firm to link shopfloor sensor telemetry with Azure IoT Hub and Microsoft PowerBI dashboards.',
    intentScore: 92,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-catherine-dubois',
    name: 'Catherine Dubois',
    jobTitle: 'VP Digital Transformation',
    companyName: 'EuroHealth Clinical',
    companyWebsite: 'www.eurohealthclinical.com',
    industry: 'Healthcare',
    companySize: '500+ employees',
    email: 'c.dubois@eurohealth.com',
    emailVerified: true,
    phone: '+33 1 4268 9100',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/catherine-dubois-health',
    sourcePlatform: 'Company Websites',
    originalPostUrl: 'https://eurohealthclinical.com/tenders/patient-portal-2026',
    originalPostSnippet: 'Corporate RFP: Overhaul of our central patient consultation portal with automated scheduling, multilingual support, and secure medical records exchange.',
    intentScore: 90,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-liam-oconnor',
    name: 'Liam O\'Connor',
    jobTitle: 'Chief Architect',
    companyName: 'Beacon Global Financial',
    companyWebsite: 'www.beaconglobal.com',
    industry: 'Finance',
    companySize: '500+ employees',
    email: 'liam.oconnor@beaconglobal.com',
    emailVerified: true,
    phone: '+44 20 7946 0881',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/liam-oconnor-architect',
    sourcePlatform: 'Company Websites',
    originalPostUrl: 'https://beaconglobal.com/rfp/disaster-recovery-cloud',
    originalPostSnippet: 'Enterprise RFP Notice: Request for proposals from certified cloud resilience consultants for multi-region disaster recovery and zero-data-loss failover architecture.',
    intentScore: 94,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },

  // 4. DIRECTORIES
  {
    id: 'lead-ana-lopez',
    name: 'Ana Lopez',
    jobTitle: 'Director of IT Systems',
    companyName: 'Brightpath Health',
    companyWebsite: 'www.brightpath.com',
    industry: 'Healthcare',
    companySize: '51 – 200 employees',
    email: 'ana.lopez@brightpath.com',
    emailVerified: true,
    phone: '+1 (555) 432-8765',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/ana-lopez-brightpath',
    sourcePlatform: 'Directories',
    originalPostUrl: 'https://directories.techprocure.org/notices/10293',
    originalPostSnippet: 'Seeking automation audit consultants for HIPAA-compliant clinical workflows.',
    intentScore: 88,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'DISCOVERED',
  },
  {
    id: 'lead-vikram-malhotra',
    name: 'Vikram Malhotra',
    jobTitle: 'Head of Procurement',
    companyName: 'Apex Energy Solutions',
    companyWebsite: 'www.apexenergy.com',
    industry: 'IT Services',
    companySize: '500+ employees',
    email: 'v.malhotra@apexenergy.com',
    emailVerified: true,
    phone: '+1 (555) 912-8830',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/vikram-malhotra-energy',
    sourcePlatform: 'Directories',
    originalPostUrl: 'https://directories.techprocure.org/notices/rfp-servicenow-8812',
    originalPostSnippet: 'Public Directory Listing: Seeking accredited consulting partner for enterprise ServiceNow ITSM implementation, asset tracking, and automated service desk workflows.',
    intentScore: 91,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-grace-hopper',
    name: 'Grace Hopper',
    jobTitle: 'Procurement Manager',
    companyName: 'CivicTech Alliance',
    companyWebsite: 'www.civictech.org',
    industry: 'Consulting',
    companySize: '51 – 200 employees',
    email: 'ghopper@civictech.org',
    emailVerified: true,
    phone: '+1 (555) 238-9901',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/grace-hopper-civic',
    sourcePlatform: 'Directories',
    originalPostUrl: 'https://directories.govprocure.org/notices/cloud-records-2026',
    originalPostSnippet: 'Vendor Directory RFP: Seeking cloud transformation consultants to migrate legacy municipal records and build citizen self-service portals.',
    intentScore: 86,
    budgetSignal: 'Approved',
    urgencyLevel: 'Medium',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-henrik-larsson',
    name: 'Henrik Larsson',
    jobTitle: 'VP Technology',
    companyName: 'Nordic Rail & Logistics',
    companyWebsite: 'www.nordicrail.eu',
    industry: 'Logistics',
    companySize: '1,000+ employees',
    email: 'h.larsson@nordicrail.eu',
    emailVerified: true,
    phone: '+46 8 555 9182',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/henrik-larsson-nordic',
    sourcePlatform: 'Directories',
    originalPostUrl: 'https://directories.europrocure.eu/rfp/rail-telematics-2026',
    originalPostSnippet: 'Official Tender Board: Seeking data engineering partner to build centralized predictive maintenance telematics pipeline across 450 railway locomotives.',
    intentScore: 93,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },

  // 5. FREELANCE PLATFORMS
  {
    id: 'lead-elena-rostova',
    name: 'Elena Rostova',
    jobTitle: 'Head of Digital Transformation',
    companyName: 'Vanguard Logistics Global',
    companyWebsite: 'www.vanguardlogistics.com',
    industry: 'Logistics',
    companySize: '500+ employees',
    email: 'e.rostova@vanguardlogistics.com',
    emailVerified: true,
    phone: '+44 20 7946 0912',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/elena-rostova-logistics',
    sourcePlatform: 'Freelance Platforms',
    originalPostUrl: 'https://www.upwork.com/jobs/~01e982183918bf',
    originalPostSnippet: 'Enterprise RFP: Need specialized systems integration team to automate supply chain telematics data into our centralized PowerBI and SharePoint portals.',
    intentScore: 91,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-carlos-mendez',
    name: 'Carlos Mendez',
    jobTitle: 'Chief Technology Officer',
    companyName: 'PayQuick Systems',
    companyWebsite: 'www.payquick.io',
    industry: 'Finance',
    companySize: '51 – 200 employees',
    email: 'carlos@payquick.io',
    emailVerified: true,
    phone: '+1 (555) 718-4920',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/carlos-mendez-payquick',
    sourcePlatform: 'Freelance Platforms',
    originalPostUrl: 'https://www.upwork.com/jobs/~01pci98214981',
    originalPostSnippet: 'Upwork Enterprise: Looking for certified cloud security specialists for automated PCI-DSS compliance posture management and penetration test remediation.',
    intentScore: 92,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-sophia-zhang',
    name: 'Sophia Zhang',
    jobTitle: 'VP Product Operations',
    companyName: 'OmniCommerce Global',
    companyWebsite: 'www.omnicommerce.com',
    industry: 'Retail',
    companySize: '201 – 500 employees',
    email: 's.zhang@omnicommerce.com',
    emailVerified: true,
    phone: '+1 (555) 881-2390',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/sophia-zhang-commerce',
    sourcePlatform: 'Freelance Platforms',
    originalPostUrl: 'https://www.upwork.com/jobs/~01netsuite8921',
    originalPostSnippet: 'Enterprise Upwork Contract ($45k budget): Need a specialized data engineering team to build bi-directional automated sync between Shopify Plus, NetSuite ERP, and HubSpot CRM.',
    intentScore: 90,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-devin-brooks',
    name: 'Devin Brooks',
    jobTitle: 'Director of DevOps',
    companyName: 'Skyward Health Labs',
    companyWebsite: 'www.skywardhealth.com',
    industry: 'Healthcare',
    companySize: '51 – 200 employees',
    email: 'd.brooks@skywardhealth.com',
    emailVerified: true,
    phone: '+1 (555) 349-1182',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/devin-brooks-devops',
    sourcePlatform: 'Freelance Platforms',
    originalPostUrl: 'https://www.upwork.com/jobs/~01hipaa81923',
    originalPostSnippet: 'Freelancer Enterprise RFP: Seeking seasoned AWS DevOps architects to implement HIPAA-compliant containerized CI/CD pipelines using Terraform and Amazon ECS.',
    intentScore: 89,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },

  // 6. CRM INTEGRATIONS
  {
    id: 'lead-robert-thorne',
    name: 'Robert Thorne',
    jobTitle: 'VP Technology Operations',
    companyName: 'OmniRetail Group',
    companyWebsite: 'www.omniretail.com',
    industry: 'Retail',
    companySize: '1,000+ employees',
    email: 'r.thorne@omniretail.com',
    emailVerified: true,
    phone: '+1 (555) 901-2345',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/robert-thorne-omni',
    sourcePlatform: 'CRM Integrations',
    originalPostUrl: 'https://crm.omniretail.com/partner-inquiries/req-8912',
    originalPostSnippet: 'Urgent CRM Sync Ticket: Looking to replace legacy middleware with an AI-driven automated pipeline to sync ERP and CRM records in real-time.',
    intentScore: 93,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-rachel-green',
    name: 'Rachel Green',
    jobTitle: 'VP Sales Operations',
    companyName: 'Vertex Global Telecom',
    companyWebsite: 'www.vertextelecom.com',
    industry: 'IT Services',
    companySize: '500+ employees',
    email: 'rachel.green@vertextelecom.com',
    emailVerified: true,
    phone: '+1 (555) 672-3341',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/rachel-green-vertex',
    sourcePlatform: 'CRM Integrations',
    originalPostUrl: 'https://crm.vertextelecom.com/inbound/lead-98234',
    originalPostSnippet: 'CRM Inbound Record: Migrating 150 sales seats from legacy HubSpot to Salesforce Enterprise Cloud. Need turnkey migration partner with data dedup and workflow automation.',
    intentScore: 94,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-daniel-kim',
    name: 'Daniel Kim',
    jobTitle: 'Chief Digital Officer',
    companyName: 'Pacific Health Partners',
    companyWebsite: 'www.pacifichealth.com',
    industry: 'Healthcare',
    companySize: '500+ employees',
    email: 'd.kim@pacifichealth.com',
    emailVerified: true,
    phone: '+1 (555) 789-2340',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/daniel-kim-health',
    sourcePlatform: 'CRM Integrations',
    originalPostUrl: 'https://crm.pacifichealth.com/leads/inquiry-4491',
    originalPostSnippet: 'CRM Sync Inbound: Seeking certified automation consultants to connect our Salesforce Health Cloud with clinic scheduling for automated SMS & voice appointment confirmations.',
    intentScore: 91,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  },
  {
    id: 'lead-oliver-fischer',
    name: 'Oliver Fischer',
    jobTitle: 'Head of Solutions Architecture',
    companyName: 'QuantBank Zurich',
    companyWebsite: 'www.quantbank.ch',
    industry: 'Finance',
    companySize: '1,000+ employees',
    email: 'o.fischer@quantbank.ch',
    emailVerified: true,
    phone: '+41 44 221 9800',
    phoneVerified: true,
    linkedinProfile: 'https://linkedin.com/in/oliver-fischer-quantbank',
    sourcePlatform: 'CRM Integrations',
    originalPostUrl: 'https://crm.quantbank.ch/enterprise/portal/inquiry-901',
    originalPostSnippet: 'Synced Inbound Account: Evaluating enterprise integration partners to connect core banking ledger with modern CRM to give private banking advisors real-time portfolio triggers.',
    intentScore: 95,
    budgetSignal: 'Approved',
    urgencyLevel: 'High',
    decisionMaker: true,
    activeRequirement: true,
    status: 'READY_TO_ENGAGE',
  }
];

async function main() {
  console.log('Seeding comprehensive 24-lead multi-platform database...');

  // 1. Organization Settings
  await prisma.organizationSetting.upsert({
    where: { id: 'default-org' },
    update: {},
    create: {
      id: 'default-org',
      companyName: 'TechNova Solutions',
      website: 'https://technova.com',
      description: 'Enterprise Microsoft 365, SharePoint & Workflow Automation Specialist',
      productsCatalog: 'Microsoft 365 migration, SharePoint Online Intranet, Power Platform automation, Teams enterprise integration',
      targetKeywords: 'Microsoft 365, SharePoint, Workflow Automation, Intranet, Power Automate, Cloud Migration',
      voiceMinutesUsed: 12450,
      voiceMinutesLimit: 20000,
      aiPersonaName: 'Ava (Sales Executive)',
      aiLanguageDefault: 'en',
      isApprovedForAi: true
    }
  });

  // 2. Active Campaign
  let campaign = await prisma.campaign.findFirst({
    where: { name: 'Product Demo Outreach' }
  });

  if (!campaign) {
    campaign = await prisma.campaign.create({
      data: {
        name: 'Product Demo Outreach',
        status: 'RUNNING',
        targetIndustry: 'IT Services & Software',
        targetLocation: 'North America & Europe',
        progressPercent: 67,
        totalLeadsCount: 1874,
        callsMadeCount: 1256,
        conversationsCount: 632,
        interestedCount: 198,
        meetingsBooked: 45
      }
    });
  }

  // 3. Upsert all 24 Discovered Leads
  for (const leadData of ALL_24_LEADS) {
    await prisma.lead.upsert({
      where: { id: leadData.id },
      update: {
        ...leadData,
        campaignId: campaign.id
      },
      create: {
        ...leadData,
        campaignId: campaign.id
      }
    });
  }

  // 4. Sample Call Logs
  const firstLead = await prisma.lead.findUnique({ where: { id: 'lead-john-smith' } });
  if (firstLead) {
    await prisma.callLog.create({
      data: {
        leadId: firstLead.id,
        campaignId: campaign.id,
        status: 'CONNECTED',
        outcome: 'MEETING_BOOKED',
        durationSeconds: 165,
        language: 'en',
        callSummary: 'Qualified: 150-user M365 & SharePoint rollout planned for next quarter. Budget approved, CTO is primary decision maker.',
        nextBestAction: 'Send SharePoint case study, confirm Thursday 3 PM demo with solutions team.',
        transcriptJson: JSON.stringify([
          { speaker: 'agent', text: "Hello John, I'm calling about your Microsoft 365 requirement posted earlier this week.", timestamp: '00:03' },
          { speaker: 'prospect', text: "Yes – we need a partner for SharePoint and workflow automation.", timestamp: '00:10' },
          { speaker: 'agent', text: "Understood. What timeline and team size are you planning for?", timestamp: '00:18' },
          { speaker: 'prospect', text: "Next quarter, around 150 users. Can we set up a call?", timestamp: '00:26' },
          { speaker: 'agent', text: "Absolutely! I have booked Thursday at 3 PM with our solutions lead. A confirmation email and calendar invite has been sent.", timestamp: '00:35' },
          { speaker: 'prospect', text: "Great, thanks Ava. Looking forward to it.", timestamp: '00:42' }
        ]),
        meetingScheduledAt: new Date(Date.now() + 86400000 * 2)
      }
    });
  }

  console.log(`Successfully seeded ${ALL_24_LEADS.length} leads across all 6 platforms!`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
